name: watchman
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0
  firebase_storage: ^11.7.0
  country_code_picker: ^3.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  geocoding: ^3.0.0
  googleapis_auth: ^1.6.0

  flutter_email_sender: ^6.0.2
  flutter_easyloading: ^3.0.5
  flutter_html: any
  flutter_local_notifications: ^17.0.0
  flutter_svg: ^2.0.9
  location: ^5.0.3
  get: ^4.6.6
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  pin_code_fields: ^8.0.1
  place_picker: ^0.10.0
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  syncfusion_flutter_datepicker: ^24.1.44
  url_launcher: ^6.2.5
  uuid: ^4.0.0
  mobile_scanner: ^3.5.6
  date_picker_timeline: ^1.2.5
  flutter_rating_bar: ^4.0.1
  flutterflow_paginate_firestore: ^1.0.3+1
  clipboard: ^0.1.3


dependency_overrides:
  webview_flutter: ^4.7.0
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: GolosText-Regular
      fonts:
        - asset: assets/fonts/GolosText-Regular.ttf

    - family: GolosText-Medium
      fonts:
        - asset: assets/fonts/GolosText-Medium.ttf

    - family: GolosText-Black
      fonts:
        - asset: assets/fonts/GolosText-Black.ttf

    - family: GolosText-Bold
      fonts:
        - asset: assets/fonts/GolosText-Bold.ttf

    - family: GolosText-ExtraBold
      fonts:
        - asset: assets/fonts/GolosText-ExtraBold.ttf

    - family: GolosText-SemiBold
      fonts:
        - asset: assets/fonts/GolosText-SemiBold.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/json/
    - assets/fonts/
